import bcrypt from "bcryptjs";
import { connectDatabase, disconnectDatabase } from "./connection";
import { env } from "../config/env";
import { UserModel } from "../models/User.model";
import { DestinationModel } from "../models/Destination.model";
import { SettingModel } from "../models/Setting.model";
import { CategoryModel } from "../models/Category.model";
import { logger } from "../utils/logger";

type DestSeed = {
  slug: string;
  name: string;
  region: string;
  state: string;
  summary: string;
  description: string;
  coverImage: string;
  highlights: string[];
};

const destinations: DestSeed[] = [
  {
    slug: "shimla",
    name: "Shimla",
    region: "Shimla Hills",
    state: "Himachal Pradesh",
    summary: "Heritage hill station with Mall Road, Kufri, Chail and Kinnaur gateway tours.",
    description:
      "Himachal's capital hill station — colonial Ridge walks, toy-train nostalgia, and day trips to Kufri, Chail, Naldehra, and Mashobra.",
    coverImage: "/images/treks/mountains-1.jpg",
    highlights: ["The Ridge", "Mall Road", "Kufri", "Chail", "Jakhoo Temple", "Viceregal Lodge"],
  },
  {
    slug: "dharamshala",
    name: "Dharamshala",
    region: "Dhauladhar Range",
    state: "Himachal Pradesh",
    summary: "Triund, Kareri, Indrahar and classic Dhauladhar treks.",
    description: "Gateway to the Dhauladhar wall — weekend ridges to alpine passes.",
    coverImage: "/images/treks/hero.jpg",
    highlights: ["Triund", "Kareri Lake", "Indrahar Pass", "Toral Pass"],
  },
  {
    slug: "kangra",
    name: "Kangra",
    region: "Dhauladhar Range",
    state: "Himachal Pradesh",
    summary: "Lam Dal, Chamunda and Bara Bhangal access trails.",
    description: "Kangra valley trailheads for sacred lakes and long crossings.",
    coverImage: "/images/treks/landscape-1.jpg",
    highlights: ["Lam Dal", "Chamunda", "Bara Bhangal"],
  },
  {
    slug: "manali",
    name: "Manali",
    region: "Kullu Valley",
    state: "Himachal Pradesh",
    summary: "Hampta, Bhrigu, Beas Kund and high Manali classics.",
    description: "Kullu–Manali base for meadows, passes and glacier walks.",
    coverImage: "/images/treks/mountains-1.jpg",
    highlights: ["Hampta Pass", "Bhrigu Lake", "Beas Kund", "Friendship Peak"],
  },
  {
    slug: "naggar",
    name: "Naggar",
    region: "Kullu Valley",
    state: "Himachal Pradesh",
    summary: "Chandrakhani Pass and quiet Kullu ridge walks.",
    description: "Heritage village base for Chandrakhani and Malana connections.",
    coverImage: "/images/treks/landscape-2.jpg",
    highlights: ["Chandrakhani Pass"],
  },
  {
    slug: "kasol",
    name: "Kasol",
    region: "Parvati Valley",
    state: "Himachal Pradesh",
    summary: "Kheerganga, Sar Pass, Rasol and Parvati forest trails.",
    description: "Parvati Valley café town and trek hub.",
    coverImage: "/images/treks/camp-1.jpg",
    highlights: ["Kheerganga", "Sar Pass", "Rasol", "Grahan"],
  },
  {
    slug: "parvati-valley",
    name: "Parvati Valley",
    region: "Parvati Valley",
    state: "Himachal Pradesh",
    summary: "Tosh and riverside village treks in Parvati.",
    description: "Scenic villages and forest walks along the Parvati river.",
    coverImage: "/images/treks/forest-1.jpg",
    highlights: ["Tosh"],
  },
  {
    slug: "malana",
    name: "Malana",
    region: "Parvati Valley",
    state: "Himachal Pradesh",
    summary: "Waichin Valley and remote Malana-side routes.",
    description: "Ancient village trails and Magic Valley approaches.",
    coverImage: "/images/treks/forest-2.jpg",
    highlights: ["Waichin Valley"],
  },
  {
    slug: "kullu",
    name: "Kullu",
    region: "Kullu Valley",
    state: "Himachal Pradesh",
    summary: "Malana, Bijli Mahadev, Shrikhand and Pin Parvati.",
    description: "Broad Kullu district trailheads for sacred and expedition treks.",
    coverImage: "/images/treks/mountains-2.jpg",
    highlights: ["Bijli Mahadev", "Malana", "Shrikhand Mahadev"],
  },
  {
    slug: "banjar",
    name: "Banjar",
    region: "Great Himalayan National Park",
    state: "Himachal Pradesh",
    summary: "Jalori, Bashleo and GHNP wilderness treks.",
    description: "Banjar–Tirthan gateway to GHNP and Jalori Pass.",
    coverImage: "/images/treks/meadow-1.jpg",
    highlights: ["Jalori Pass", "Bashleo Pass", "GHNP"],
  },
  {
    slug: "jalori-pass",
    name: "Jalori Pass",
    region: "Great Himalayan National Park",
    state: "Himachal Pradesh",
    summary: "Serolsar Lake day trek from Jalori Pass.",
    description: "High meadow day walks from Jalori.",
    coverImage: "/images/treks/landscape-3.jpg",
    highlights: ["Serolsar Lake"],
  },
  {
    slug: "jalori",
    name: "Jalori",
    region: "Great Himalayan National Park",
    state: "Himachal Pradesh",
    summary: "Raghupur Fort and Jalori ridge walks.",
    description: "Short heritage and meadow trails near Jalori.",
    coverImage: "/images/treks/mountains-3.jpg",
    highlights: ["Raghupur Fort"],
  },
  {
    slug: "chamba",
    name: "Chamba",
    region: "Pir Panjal",
    state: "Himachal Pradesh",
    summary: "Kugti Pass and Sach Pass alpine crossings.",
    description: "Chamba district high passes and shepherd trails.",
    coverImage: "/images/treks/mountains-1.jpg",
    highlights: ["Kugti Pass", "Sach Pass"],
  },
  {
    slug: "bharmour",
    name: "Bharmour",
    region: "Pir Panjal",
    state: "Himachal Pradesh",
    summary: "Manimahesh Kailash pilgrimage trek.",
    description: "Sacred Manimahesh yatra base in Bharmour.",
    coverImage: "/images/treks/india-1.jpg",
    highlights: ["Manimahesh Kailash"],
  },
  {
    slug: "kinnaur",
    name: "Kinnaur",
    region: "Kinnaur",
    state: "Himachal Pradesh",
    summary: "Rupin, Bhaba, Charang, Borasu and Lamkhaga.",
    description: "High Kinnaur passes linking Garhwal and Spiti.",
    coverImage: "/images/treks/mountains-2.jpg",
    highlights: ["Rupin Pass", "Bhaba Pass", "Charang Valley"],
  },
  {
    slug: "kalpa",
    name: "Kalpa",
    region: "Kinnaur",
    state: "Himachal Pradesh",
    summary: "Kinner Kailash circuit from Kalpa.",
    description: "Kinnaur Kailash views and sacred circuit trails.",
    coverImage: "/images/treks/landscape-1.jpg",
    highlights: ["Kinner Kailash"],
  },
  {
    slug: "janglik",
    name: "Janglik",
    region: "Kinnaur",
    state: "Himachal Pradesh",
    summary: "Buran Ghati trailhead at Janglik.",
    description: "Classic Buran Ghati start village.",
    coverImage: "/images/treks/camp-1.jpg",
    highlights: ["Buran Ghati"],
  },
  {
    slug: "sirmaur",
    name: "Sirmaur",
    region: "Sirmaur",
    state: "Himachal Pradesh",
    summary: "Churdhar Peak — highest in southern Himachal.",
    description: "Forest ridge trek to Churdhar temple peak.",
    coverImage: "/images/treks/forest-1.jpg",
    highlights: ["Churdhar Peak"],
  },
  {
    slug: "spiti",
    name: "Spiti",
    region: "Spiti Valley",
    state: "Himachal Pradesh",
    summary: "Parang La, Pin Bhaba, Kanamo, Chandratal and more.",
    description: "Cold desert high passes, lakes and village trails.",
    coverImage: "/images/treks/mountains-3.jpg",
    highlights: ["Chandratal", "Kanamo Peak", "Parang La", "Dhankar Lake"],
  },
  {
    slug: "pin-valley",
    name: "Pin Valley",
    region: "Spiti Valley",
    state: "Himachal Pradesh",
    summary: "Mudh Village and Pin Valley walks.",
    description: "Quiet Pin Valley villages and valley floors.",
    coverImage: "/images/treks/meadow-1.jpg",
    highlights: ["Mudh Village"],
  },
  // Uttarakhand hubs
  {
    slug: "sankri",
    name: "Sankri",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Kedarkantha, Har Ki Dun, Bali Pass and Govind National Park treks.",
    description: "Classic winter and alpine trailhead for western Garhwal.",
    coverImage: "/images/treks/mountains-1.jpg",
    highlights: ["Kedarkantha", "Har Ki Dun", "Bali Pass", "Phulara Ridge"],
  },
  {
    slug: "gangotri",
    name: "Gangotri",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Gaumukh Tapovan, Kedartal, Kalindi Khal and glacier approaches.",
    description: "Sacred Gangotri corridor for high Garhwal expeditions.",
    coverImage: "/images/treks/mountains-2.jpg",
    highlights: ["Gaumukh Tapovan", "Kedartal", "Kalindi Khal"],
  },
  {
    slug: "uttarkashi",
    name: "Uttarkashi",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Dayara Bugyal, Dodital and Darwa Pass meadows.",
    description: "Uttarkashi district bugyals and forest ridge walks.",
    coverImage: "/images/treks/meadow-1.jpg",
    highlights: ["Dayara Bugyal", "Dodital", "Darwa Pass"],
  },
  {
    slug: "joshimath",
    name: "Joshimath",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Valley of Flowers, Kuari Pass and Pangarchulla.",
    description: "Joshimath–Auli gateway to Chamoli alpine meadows.",
    coverImage: "/images/treks/landscape-1.jpg",
    highlights: ["Valley of Flowers", "Kuari Pass", "Pangarchulla"],
  },
  {
    slug: "govindghat",
    name: "Govindghat",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Hemkund Sahib pilgrimage trek base.",
    description: "Trailhead for Hemkund Sahib and Valley of Flowers access.",
    coverImage: "/images/treks/india-1.jpg",
    highlights: ["Hemkund Sahib"],
  },
  {
    slug: "auli",
    name: "Auli",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Gorson, Tali Lake and Gurson Bugyal day walks.",
    description: "Ski meadow village with easy alpine day treks.",
    coverImage: "/images/treks/landscape-2.jpg",
    highlights: ["Gorson Bugyal", "Tali Lake"],
  },
  {
    slug: "lohajung",
    name: "Lohajung",
    region: "Kumaon",
    state: "Uttarakhand",
    summary: "Roopkund, Brahmatal and Ali Bedni Bugyal.",
    description: "Famous Roopkund trailhead in Chamoli.",
    coverImage: "/images/treks/mountains-3.jpg",
    highlights: ["Roopkund", "Brahmatal", "Ali Bedni"],
  },
  {
    slug: "bageshwar",
    name: "Bageshwar",
    region: "Kumaon",
    state: "Uttarakhand",
    summary: "Pindari, Kafni and Sunderdhunga glacier approaches.",
    description: "Kumaon glacier trail hub.",
    coverImage: "/images/treks/camp-1.jpg",
    highlights: ["Pindari Glacier", "Kafni Glacier", "Sunderdhunga"],
  },
  {
    slug: "munsiyari",
    name: "Munsiyari",
    region: "Kumaon",
    state: "Uttarakhand",
    summary: "Milam, Ralam, Panchachuli and Khaliya Top.",
    description: "Eastern Kumaon high Himalaya base.",
    coverImage: "/images/treks/mountains-1.jpg",
    highlights: ["Milam Glacier", "Panchachuli", "Khaliya Top"],
  },
  {
    slug: "pithoragarh",
    name: "Pithoragarh",
    region: "Kumaon",
    state: "Uttarakhand",
    summary: "Adi Kailash sacred circuit approaches.",
    description: "Far-east Uttarakhand pilgrimage and border treks.",
    coverImage: "/images/treks/india-1.jpg",
    highlights: ["Adi Kailash"],
  },
  {
    slug: "dharchula",
    name: "Dharchula",
    region: "Kumaon",
    state: "Uttarakhand",
    summary: "Om Parvat darshan trek base.",
    description: "Dharchula gateway to Om Parvat.",
    coverImage: "/images/treks/landscape-3.jpg",
    highlights: ["Om Parvat"],
  },
  {
    slug: "mussoorie",
    name: "Mussoorie",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Nag Tibba weekend ridge trek.",
    description: "Closest Garhwal weekend peak from Dehradun.",
    coverImage: "/images/treks/forest-1.jpg",
    highlights: ["Nag Tibba"],
  },
  {
    slug: "dhanaulti",
    name: "Dhanaulti",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Surkanda Devi temple day trek.",
    description: "Short sacred ridge walk near Dhanaulti.",
    coverImage: "/images/treks/forest-2.jpg",
    highlights: ["Surkanda Devi"],
  },
  {
    slug: "chopta",
    name: "Chopta",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Tungnath, Chandrashila and Deoria Tal.",
    description: "Mini Switzerland of India — classic easy Garhwal treks.",
    coverImage: "/images/treks/meadow-1.jpg",
    highlights: ["Tungnath", "Chandrashila", "Deoria Tal"],
  },
  {
    slug: "sari-village",
    name: "Sari Village",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Deoria Tal lake trailhead.",
    description: "Village base for Deoria Tal.",
    coverImage: "/images/treks/landscape-1.jpg",
    highlights: ["Deoria Tal"],
  },
  {
    slug: "rudraprayag",
    name: "Rudraprayag",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Kartik Swami ridge temple trek.",
    description: "Short Garhwal temple ridge near Rudraprayag.",
    coverImage: "/images/treks/india-1.jpg",
    highlights: ["Kartik Swami"],
  },
  {
    slug: "ghuttu",
    name: "Ghuttu",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Panwali Kantha meadow trek.",
    description: "Ghuttu trailhead for Panwali Kantha.",
    coverImage: "/images/treks/meadow-1.jpg",
    highlights: ["Panwali Kantha"],
  },
  {
    slug: "ukhimath",
    name: "Ukhimath",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Madhyamaheshwar Panch Kedar trek.",
    description: "Ukhimath base for Madhyamaheshwar.",
    coverImage: "/images/treks/camp-1.jpg",
    highlights: ["Madhyamaheshwar"],
  },
  {
    slug: "gopeshwar",
    name: "Gopeshwar",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Rudranath Panch Kedar trek.",
    description: "Gopeshwar approach to Rudranath.",
    coverImage: "/images/treks/forest-1.jpg",
    highlights: ["Rudranath"],
  },
  {
    slug: "helang",
    name: "Helang",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Kalpeshwar easy Panch Kedar walk.",
    description: "Helang trailhead for Kalpeshwar.",
    coverImage: "/images/treks/forest-2.jpg",
    highlights: ["Kalpeshwar"],
  },
  {
    slug: "badrinath",
    name: "Badrinath",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Satopanth Lake and Neelkanth base camp.",
    description: "High alpine lakes above Badrinath.",
    coverImage: "/images/treks/mountains-2.jpg",
    highlights: ["Satopanth Lake", "Neelkanth"],
  },
  {
    slug: "harsil",
    name: "Harsil",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Lamkhaga Pass approach from Harsil.",
    description: "Quiet Bhagirathi valley gateway.",
    coverImage: "/images/treks/landscape-2.jpg",
    highlights: ["Lamkhaga Pass"],
  },
  {
    slug: "govind-wildlife-sanctuary",
    name: "Govind Wildlife Sanctuary",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Bamsaru Khal and sanctuary alpine routes.",
    description: "Protected Govind National Park wilderness.",
    coverImage: "/images/treks/forest-1.jpg",
    highlights: ["Bamsaru Khal"],
  },
  {
    slug: "yamunotri",
    name: "Yamunotri",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Bandarpunch base camp approaches.",
    description: "Yamunotri valley alpine base.",
    coverImage: "/images/treks/mountains-3.jpg",
    highlights: ["Bandarpunch"],
  },
  {
    slug: "kedarnath",
    name: "Kedarnath",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Vasuki Tal above Kedarnath.",
    description: "Sacred Kedarnath alpine lake approaches.",
    coverImage: "/images/treks/india-1.jpg",
    highlights: ["Vasuki Tal"],
  },
  {
    slug: "gaurikund",
    name: "Gaurikund",
    region: "Garhwal",
    state: "Uttarakhand",
    summary: "Kedarnath yatra trail from Gaurikund.",
    description: "Roadhead for the Kedarnath pilgrimage trek.",
    coverImage: "/images/treks/landscape-3.jpg",
    highlights: ["Kedarnath Trek"],
  },
];

async function seed() {
  await connectDatabase();

  const email = env.SEED_SUPERADMIN_EMAIL || "admin@indiaholidaydestinations.com";
  const password = env.SEED_SUPERADMIN_PASSWORD || "ChangeMe@12345";
  const name = env.SEED_SUPERADMIN_NAME || "Super Admin";

  const passwordHash = await bcrypt.hash(password, env.BCRYPT_ROUNDS);
  await UserModel.findOneAndUpdate(
    { email },
    {
      name,
      email,
      passwordHash,
      role: "super_admin",
      isEmailVerified: true,
      status: "active",
      deletedAt: null,
    },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );
  logger.info("Super admin ready", { email });

  for (const dest of destinations) {
    await DestinationModel.findOneAndUpdate(
      { slug: dest.slug },
      {
        ...dest,
        trekCount: 0,
        bestSeasons: ["spring", "summer", "autumn"],
        altitudeRange: { min: 4000, max: 19000 },
        gallery: [dest.coverImage],
        status: "published",
        deletedAt: null,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );
  }
  logger.info("Destinations seeded", { count: destinations.length });

  await CategoryModel.findOneAndUpdate(
    { slug: "weekend-treks" },
    {
      slug: "weekend-treks",
      name: "Weekend Treks",
      type: "trek",
      description: "Short Himalayan escapes",
      deletedAt: null,
    },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );

  await SettingModel.findOneAndUpdate(
    { key: "site.name" },
    { key: "site.name", value: "India Holiday Destinations", group: "general" },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );
  await SettingModel.findOneAndUpdate(
    { key: "site.currency" },
    { key: "site.currency", value: "INR", group: "general" },
    { upsert: true, new: true, setDefaultsOnInsert: true },
  );

  logger.info("Seed complete");
  await disconnectDatabase();
}

seed().catch(async (error) => {
  logger.error("Seed failed", { error });
  await disconnectDatabase();
  process.exit(1);
});
